[package]
name = "mondrian"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.31"
inputbot = "0.6"
lazy_static = "1.4"
log = "0.4.20"
serde_json = "1.0.108"
regex = "1.3.9"
log4rs = "1.3.0"
dirs = "5.0.1"
clap = { version = "4.1.6", features = ["derive"] }
notify-rust = "4"
tray-icon = "0.14.3"

[dependencies.windows]
version = "0.56"
features = [
    "Win32_Foundation",
    "Win32_System_ProcessStatus",
    "Win32_UI_Accessibility",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
    'Win32_UI_Input_KeyboardAndMouse',
    "Win32_System_Threading",
    "Win32_UI_Controls",
]

[build-dependencies]
winresource = "0.1.17"
