[layout]
tiling_strategy = "golden_ratio" # can be "golden_ratio", "horizontal" or "vertical"
tiles_padding = 4                # padding between tiles, it must be between 0 and 60
border_padding = 4               # padding between border and tiles, it must be between 0 and 60

[layout.golden_ratio] # if tiling_strategy = "golden_ratio"
clockwise = true # true = clockwise, false = counterclockwise
vertical = false # if true, the first split will be vertical

[layout.horizontal] # if tiling_strategy = "horizontal"
start_right = true # direction of the first split
toogle = false     # if toggled, the direction of the next split will be opposite

[layout.vertical] # if tiling_strategy = "vertical"
start_down = true # direction of the first split
toogle = false    # if toggled, the direction of the next split will be opposite

[modules]
keybindings = true # enable the keybindings module
overlay = true     # enable the overlay module

[keybindings] # if keybindings = true
default_modifier = "ALT" # default modifier for keybindings, it can be "CTRL", "ALT", "SHIFT", "WIN" or any combination of them (e.g. "CTRL+ALT+SHIFT")
bindings = [
    { key = "X", action = "quit" }, # e.g. when pressing <default_modifier>+X, the action will be "quit"
    { modifier = "CTRL", key = "R", action = "refresh-config" }, # e.g. when pressing CTRL+R, the action will be "refresh"
]

[overlay] # if overlay = true
thickness = 4         # thickness of the border
color = [0, 150, 148] # color of the border
padding = 0           # padding between the border and the tiles

[advanced]
refresh_time = 50 # in milliseconds, set the time between each refresh. Values below 30 are not recommended, and probably there is no benefit with such a low value

[rules]
filters = [
    # { title = "Title", exename = "app.exe", classname ="ApplicationWindow" }, # match any window with a title="Title" and exename="app.exe" and classname="ApplicationWindow"
    # { title = "Title" }, # match any window with a title="Title" (title, exename, classname are optional, but at least one of them must be specified)
    # { title = "/Title[0-9]/" }, # match any window with a title that matches the regex "/Title[0-9]/" (you can use regex in title, exename and classname by enclosing them in slashes)
]
